### ISSUE TITLE
Take an argument to check for duplicated dependencies

### ISSUE THREAD

**Issue by alexthemark** [atlassian/yarn-deduplicate#21]
I'd like to have an option to check for duplicated dependencies, and then fail my CI build if there are duplicate dependencies. Right now I have to do this by checking if the length of listed deduplicated dependencies is equal to 0. 

Would you take a third command, `yarn deduplicate --check /path/to/yarn.lock` which would `process.exit(1)` if there are duplicated dependencies, and `process.exit(0)` if there are none? I'm happy to submit a PR if you'd take the change!

**Comment by scinos** [comment]
Awesome idea @alexthemark!

I think it will be better as a secondary arg to `--list`. For example, something like `yarn --list --fail /path/to/yarn.lock` will print the list of duplicated **and** exit with `1` so you can use it in CI. The reason is that if we implement `yarn deduplicate --check`, you'll almost always want to do `--list` afterwards to see why it failed. So why not include that list in the original command anyway?

What do you think? Happy to take a PR for this if you are interested.
