### ISSUE TITLE
Breaking change with recent Yarn update

### ISSUE THREAD

**Issue by mockdeep** [atlassian/yarn-deduplicate#85]
[This PR](https://github.com/atlassian/yarn-deduplicate/pull/72) bumped up the required `yarn` version for `yarn-deduplicate`, which breaks a lot of builds for us. A lot of the [CircleCI build images](https://hub.docker.com/layers/circleci/ruby/2.6.3-stretch-node-browsers/images/sha256-8b610fc0693486e611e58c4d4d2394509023236cb04c34f0a62fe675a2545fe5?context=explore) still have an older yarn version by default, `1.17.3` in our case. Would it be okay to loosen the version requirement using `>=` similar to the `node` engine?

**Comment by sokra** [comment]
It also broke our builds on travis CI (yarn: 1.3.2) and appveyor (yarn: 1.21.1).

**Comment by scinos** [comment]
Should be fixed in `2.1.1`. It now requires `yarn >= 1`.

For consumers of this package, `yarn 1.0.0` or above should be enough. It should work in all examples listed in this issue.

For contributors, yarn 1.0.0 or above will honor the version policy (https://classic.yarnpkg.com/en/docs/cli/policies/#toc-policies-set-version), so when working in the repo it should use `1.22.4` as specified in `.yarnrc` path.
